config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :posts do
    resources :comments
  end

  get 'posts/view/:id', to: 'posts#ditum', as: 'ditum'

  namespace :admin do
    root 'home#index'
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	has_one_attached :image
	has_many :comments, dependent: :destroy
	has_one :view_count, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :post
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  def index
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
	def new
		@post = Post.new
	end

	def index
		@posts = Post.all
	end
	
	def create
		@post = Post.new(post_params)
		@post.save
		redirect_to admin_post_path(@post)
	end

	def edit
		@post = Post.find(params[:id])
	end
	
	def show
		@post = Post.find(params[:id])
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to admin_posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :image)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:status])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = Comment.new(post: @post, content: comment_params[:content])
		@comment.save
		redirect_to post_path(@post)
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.order(:title).page params[:page]
  end

  def ditum
    @post = Post.find(params[:id])
    if @post.view_count.present?
      @ditum = @post.view_count.ditum.to_i + 1
      @post.view_count.update(ditum: @ditum)
      redirect_to post_path(@post)
    else
      @view_count = @post.create_view_count(ditum: 1)
      @view_count.save
      redirect_to post_path(@post)
    end
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/home/index.html.erb
<h1>Admin::Home#index</h1>
<p>Find me in app/views/admin/home/index.html.erb</p>

app/views/admin/posts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 mx-auto">
			<%= form_for [:admin, @post] do |f| %>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :content %>
				<%= f.text_area :content, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.submit class: 'btn btn-primary' %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/admin/posts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<%= link_to 'New Post', new_admin_post_path, class: 'btn btn-success' %>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<table class="table table-bordered">
				<tr>
					<th>Title</th>
					<th>Content</th>
					<th>Edit</th>
					<th>Delete</th>
				</tr>
				<% @posts.each do |post| %>
				<tr>
					<td><%= link_to post.title, admin_post_path(post) %></td>
					<td><%= post.content %></td>
					<td><%= link_to 'Edit', edit_admin_post_path(post), class: 'btn btn-info' %></td>
					<td><%= button_to 'Delete', [:admin, post], method: :delete, class: 'btn btn-danger' %></td>
				</tr>
				
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/admin/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 mx-auto">
			<%= form_for [:admin, @post] do |f| %>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :content %>
				<%= f.text_area :content, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :image %>
				<%= f.file_field :image, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.submit class: 'btn btn-primary' %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<% if @post.image.present? %>
			<%= image_tag @post.image, width: '100%' %>
			<% end %>
		</div>
		<div class="col-md-6">
			<h2><%= @post.title %></h2>
			<p><%= @post.content %></p>
		</div>
	</div>
</div>

app/views/admin/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', admin_root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Posts', admin_posts_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
      </ul>
      <span class="navbar-text">
        Navbar text with an inline element
      </span>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<% if current_user %>
	<p>
		<%= current_user.status %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp77</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if controller_path =~/^admin\// %>
      <%= render 'admin/shared/header' %>
    <% else %>
      <%= render 'shared/header' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">
	<div class="col">
		<table class="table table-bordered">
			<tr>
				<th>Title</th>
				<th>Content</th>
			</tr>
		<% @posts.each do |post| %>
			<tr>
				<td><%= link_to post.title, ditum_path(post) %></td>
				<td><%= link_to post.content, ditum_path(post) %></td>
			</tr>	
		<% end %>
		</table>
		<%= paginate @posts %>
	</div>
	</div>
</div>

app/views/posts/show.html.erb
<p>
	<%= @post.title %>
</p>

<% if @post.view_count.present? %>
	<p>Ditel en <%= @post.view_count.ditum %> mard</p>
<p>
	<%= @post.content %>
</p>
<% end %>

<%= form_for [@post, @post.comments.build] do |f| %>
	<%= f.text_area :content %>
	<%= f.submit %>
<% end %>

<p>
	<b><%= @post.comments.count %></b>
</p>

<% @post.comments.each do |comment| %>
	<p>
		<%= comment.content %>
	</p>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>